allow_zero_lintable_files: true
disabled_rules:
  - object_literal
  - file_length
  - file_header
  - identifier_name
  - force_cast
  - force_try
  - todo
  - cyclomatic_complexity
  - multiple_closures_with_trailing_closure
  - notification_center_detachment
  - function_parameter_count
  - large_tuple
  - class_delegate_protocol
  - valid_ibinspectable
  - strong_iboutlet
  - nesting
  # - discarded_notification_center_observer
opt_in_rules:
  - anyobject_protocol
  - array_init
  - attributes
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  # - discouraged_object_literal
  # - empty_count # https://github.com/realm/SwiftLint/issues/827
  - empty_string
  - explicit_init
  - extension_access_modifier
  - fatal_error_message
  - file_header
  - file_name_no_space
  - first_where
  - identical_operands
  - implicit_getter
  - implicit_return
  - inclusive_language
  - joined_default_parameter
  - leading_whitespace
  - legacy_random
  - let_var_whitespace
  - literal_expression_end_indentation
  - lower_acl_than_parent
  - multiline_arguments
  - multiline_function_chains
  - nimble_operator
  - object_literal
  - operator_usage_whitespace
  - operator_whitespace
  - overridden_super_call
  - pattern_matching_keywords
  - private_action
  - private_outlet
  - private_subject
  - prohibited_super_call
  - protocol_property_accessors_order
  - quick_discouraged_call
  - quick_discouraged_focused_test
  - quick_discouraged_pending_test
  - raw_value_for_camel_cased_codable_enum
  - redundant_objc_attribute
  - reduce_boolean
  - redundant_nil_coalescing
  - redundant_set_access_control
  - redundant_type_annotation
  - redundant_void_return
  - return_arrow_whitespace
  - single_test_class
  - sorted_first_last
  - sorted_imports
  - switch_case_on_newline
  - toggle_bool
  - unneeded_break_in_switch
  - unneeded_parentheses_in_closure_argument
  - unowned_variable_capture
  - unused_declaration
  - unused_import
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - void_return
  - yoda_condition
  - legacy_multiple

included: # paths to include during linting
    - kagoshima-ios

excluded:
  - .bundle
  - Carthage
  - fastlane
  - firebase
  - Pods
  - vendor
  - "*Tests"

line_length:
  warning: 400
  error: 2000
  ignores_comments: true
type_body_length:
  - 600 # warning
  - 700 # error
type_name:
  min_length: 1
  max_length: 75
function_body_length:
  warning: 400
  error: 500
