# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Run Build"
  lane :build do
    build_staging
  end

  desc "Run Build Staging"
  lane :build_staging do
    build_app(
      scheme: "ChatGPT",
      clean: true,
      destination: "generic/platform=iOS",
      configuration: "Staging",
      skip_package_ipa: true,
      skip_archive: true,
      skip_codesigning: true
    )
  end

  desc "Run Test"
  lane :test do
    scan(
      scheme: "ChatGPT",
      configuration: "Debug",
      code_coverage: true
      )
  end

  lane :tests do
    run_tests(workspace: "ChatGPT.xcworkspace",
              devices: ["iPhone 12"],
              scheme: "ChatGPTTests")
   end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end

end
