# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  
  lane :lint do
    cocoapods
    danger
  end

  lane :build do
    update_code_signing_settings(
      use_automatic_signing: true,
      path: "ChatGPT.xcodeproj",
      bundle_identifier: "manuchim.ChatGPT"
    )

    xcodebuild(
      xcodeproj: "ChatGPT.xcodeproj",
      scheme: "ChatGPT",
      configuration: "Release",
      clean: true,
      build: true,
      destination: "generic/platform=iOS",
    )
   end

  lane :tests do
    run_tests(workspace: "ChatGPT.xcworkspace",
              devices: ["iPhone 12"],
              scheme: "ChatGPTTests")
   end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end

end
